import type { DroneSpec } from '@opticone/shared'

/**
 * C-01 seed dataset. All numbers from public sources (sourceUrl), SI units,
 * 1:1 scale. Estimated fields are marked in the name of honesty: where a
 * manufacturer does not publish a figure (e.g. Switchblade battery Wh) the
 * value is derived from published endurance and mass, and the sourceUrl
 * points at the best public reference for the aircraft.
 */
export const SEED_DRONES: DroneSpec[] = [
  {
    id: 'mavic3',
    name: 'DJI Mavic 3 (recon quad)',
    class: 'multirotor',
    massKg: 0.895,
    dimensionsM: { x: 0.3475, y: 0.1077, z: 0.283 },
    batteryWh: 77,
    enduranceS: 2760,
    cruiseMps: 15,
    maxMps: 21,
    ceilingM: 6000,
    windLimitMps: 12,
    payloadKg: 0,
    controlRangeM: 15000,
    costCredits: 2000,
    sourceUrl: 'https://www.dji.com/mavic-3/specs',
  },
  {
    id: 'fpv-strike',
    name: 'FPV strike quad (7-inch class)',
    class: 'multirotor',
    massKg: 1.5,
    dimensionsM: { x: 0.35, y: 0.12, z: 0.35 },
    batteryWh: 66,
    enduranceS: 600,
    cruiseMps: 25,
    maxMps: 40,
    ceilingM: 3000,
    windLimitMps: 10,
    payloadKg: 0.8,
    controlRangeM: 10000,
    costCredits: 500,
    sourceUrl: 'https://en.wikipedia.org/wiki/FPV_drone',
  },
  {
    id: 'switchblade300',
    name: 'AeroVironment Switchblade 300',
    class: 'loitering-munition',
    massKg: 2.5,
    dimensionsM: { x: 0.76, y: 0.12, z: 0.495 },
    batteryWh: 60,
    enduranceS: 900,
    cruiseMps: 28,
    maxMps: 44,
    ceilingM: 4500,
    windLimitMps: 12,
    payloadKg: 0.3,
    controlRangeM: 10000,
    costCredits: 60000,
    sourceUrl: 'https://en.wikipedia.org/wiki/AeroVironment_Switchblade',
  },
  {
    id: 'shahed136',
    name: 'Shahed-136 (delta-wing loitering munition)',
    class: 'loitering-munition',
    massKg: 200,
    dimensionsM: { x: 2.5, y: 0.5, z: 3.5 },
    batteryWh: null,
    fuelKg: 60,
    burnKgPerH: 5,
    enduranceS: 43200,
    cruiseMps: 41.7,
    maxMps: 51.4,
    ceilingM: 4000,
    windLimitMps: 15,
    payloadKg: 40,
    controlRangeM: 0,
    costCredits: 20000,
    sourceUrl: 'https://en.wikipedia.org/wiki/HESA_Shahed_136',
  },
  {
    id: 'tb2',
    name: 'Baykar Bayraktar TB2',
    class: 'fixed-wing',
    massKg: 700,
    dimensionsM: { x: 12, y: 2, z: 6.5 },
    batteryWh: null,
    fuelKg: 220,
    burnKgPerH: 8,
    enduranceS: 97200,
    cruiseMps: 36,
    maxMps: 61.7,
    ceilingM: 7620,
    windLimitMps: 20,
    payloadKg: 150,
    controlRangeM: 300000,
    costCredits: 5000000,
    sourceUrl: 'https://en.wikipedia.org/wiki/Bayraktar_TB2',
  },
  {
    id: 'xq58-valkyrie',
    name: 'Kratos XQ-58A Valkyrie',
    class: 'fixed-wing',
    massKg: 2722,
    dimensionsM: { x: 9.14, y: 1.5, z: 8.2 },
    batteryWh: null,
    // Fuel load unpublished; derived from the ~3,000 nmi range at Mach 0.72.
    fuelKg: 1000,
    burnKgPerH: 160,
    enduranceS: 22500,
    cruiseMps: 247,
    maxMps: 290,
    ceilingM: 14000,
    windLimitMps: 25,
    payloadKg: 544,
    controlRangeM: 300000,
    costCredits: 4000000,
    sourceUrl: 'https://en.wikipedia.org/wiki/Kratos_XQ-58_Valkyrie',
  },
  {
    id: 'flycart30',
    name: 'DJI FlyCart 30 (cargo lifter)',
    class: 'cargo',
    massKg: 95,
    dimensionsM: { x: 2.8, y: 0.947, z: 3.085 },
    batteryWh: 3970,
    enduranceS: 1080,
    cruiseMps: 15,
    maxMps: 20,
    ceilingM: 6000,
    windLimitMps: 12,
    payloadKg: 30,
    controlRangeM: 20000,
    costCredits: 30000,
    sourceUrl: 'https://www.dji.com/flycart-30/specs',
  },
  {
    id: 'ore-miner',
    name: 'Ore miner (fictional, Agras T40 physics)',
    class: 'mining',
    massKg: 42,
    dimensionsM: { x: 2.184, y: 0.732, z: 1.926 },
    batteryWh: 2000,
    enduranceS: 1800,
    cruiseMps: 10,
    maxMps: 14,
    ceilingM: 3000,
    windLimitMps: 10,
    payloadKg: 20,
    controlRangeM: 8000,
    costCredits: 15000,
    sourceUrl: 'https://www.dji.com/t40/specs',
  },
]
